/*
 * generated by Xtext
 */
package org.modelexecution;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class AlfRuntimeModule extends org.modelexecution.AbstractAlfRuntimeModule {

}
