/*
 * generated by Xtext
 */
package org.modelexecution.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import org.modelexecution.ui.internal.AlfActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class AlfExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return AlfActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return AlfActivator.getInstance().getInjector(AlfActivator.ORG_MODELEXECUTION_ALF);
	}
	
}
