/*
 * generated by Xtext
 */
package org.modelexecution.ui.contentassist

import org.modelexecution.ui.contentassist.AbstractAlfProposalProvider

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
class AlfProposalProvider extends AbstractAlfProposalProvider {
}
