/*
 * generated by Xtext
 */
package org.modelexecution.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class AlfUiModule extends org.modelexecution.ui.AbstractAlfUiModule {
	public AlfUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
